"""The built distribution must declare the licence the repository carries.

A release SBOM can only report what the distribution's own metadata says. This
project shipped a MIT `LICENSE` file while declaring no licence at all, so its
own component appeared in the CycloneDX SBOM with no licence and the release
licence gate classified it as undecidable -- correctly, since undeclared is not
permission. These tests pin the metadata rather than the gate's reaction to it.

Metadata and licence bytes are inspected in a wheel generated by the declared
uv backend, using the pinned existing tool offline. No native code is compiled
and no project dependency is installed or imported. Missing/incompatible tools
fail the test rather than converting missing build evidence into a skip.
"""

from __future__ import annotations

import email
import subprocess
import tempfile
import zipfile
import tomllib
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
NATIVE_DISTRIBUTION_DIRECTORIES = (
    REPOSITORY_ROOT / "rust" / "decision_receipt",
    REPOSITORY_ROOT / "rust" / "token_counter",
)


def _pyproject() -> dict:
    with open(REPOSITORY_ROOT / "pyproject.toml", "rb") as handle:
        return tomllib.load(handle)


def test_native_distribution_license_metadata_matches_bundled_license() -> None:
    root_license = (REPOSITORY_ROOT / "LICENSE").read_bytes()

    for distribution_directory in NATIVE_DISTRIBUTION_DIRECTORIES:
        with open(distribution_directory / "pyproject.toml", "rb") as handle:
            pyproject = tomllib.load(handle)
        with open(distribution_directory / "Cargo.toml", "rb") as handle:
            cargo_package = tomllib.load(handle)["package"]

        assert pyproject["build-system"] == {
            "build-backend": "maturin",
            "requires": ["maturin==1.15.0"],
        }
        project = pyproject["project"]
        assert project.get("license") == "MIT"
        assert project.get("license-files") == ["LICENSE"]
        assert cargo_package.get("license") == "MIT"
        assert cargo_package.get("license-file") == "LICENSE"
        assert (distribution_directory / "LICENSE").read_bytes() == root_license


def test_license_declaration_matches_the_repository_license_file() -> None:
    project = _pyproject()["project"]
    license_text = (REPOSITORY_ROOT / "LICENSE").read_text(encoding="utf-8")

    assert project["license"] == "MIT"
    assert project["license-files"] == ["LICENSE"]
    assert license_text.startswith("MIT License")


def test_build_backend_floor_supports_the_license_expression() -> None:
    """The build tool is pinned and removes the bundled LGPL setuptools path."""
    build_system = _pyproject()["build-system"]
    assert build_system == {"build-backend": "uv_build", "requires": ["uv_build==0.12.5"]}
    assert "setuptools" not in (REPOSITORY_ROOT / "requirements-opencode-review-ci.in").read_text()


def test_generated_metadata_declares_the_license(tmp_path) -> None:
    # A real file exercises the core/native ownership exclusion without compiling it.
    with tempfile.NamedTemporaryFile(suffix=".so", dir=REPOSITORY_ROOT / "contextual_orchestrator"):
        subprocess.run(["uv", "build", "--wheel", "--offline", "--no-build-isolation",
                        "--out-dir", str(tmp_path)], cwd=REPOSITORY_ROOT, check=True,
                       capture_output=True, text=True)
    wheel, = tmp_path.glob("*.whl")
    with zipfile.ZipFile(wheel) as archive:
        metadata_path, = [name for name in archive.namelist() if name.endswith(".dist-info/METADATA")]
        metadata = email.message_from_bytes(archive.read(metadata_path))
        assert metadata.get("License-Expression") == "MIT"
        assert "LICENSE" in " ".join(metadata.get_all("License-File") or [])
        assert archive.read(metadata_path.removesuffix("METADATA") + "licenses/LICENSE") == (REPOSITORY_ROOT / "LICENSE").read_bytes()
        assert not any(name.endswith((".so", ".pyd")) for name in archive.namelist())
