"""Public package exports for the contextual orchestration runtime."""

from .batch_routing import (
    BatchJob,
    BatchRequest,
    BatchResultItem,
    EmbeddingBatchRequest,
    EmbeddingBatchResultItem,
    LocalBatchBackend,
    LocalEmbeddingBatchBackend,
    PgLlmBatchBackend,
    PgLlmBatchEmbeddingBackend,
    RoutingDecision,
    RoutingHints,
    RoutingPolicy,
    build_embeddings_jsonl_body,
    cheapest_upstream,
    heuristic_embedding,
)
from .cost_ledger import (
    ATTRIBUTION_DIMENSIONS,
    AttributionDimensions,
    CostLedger,
    InMemoryLedgerStore,
    InMemoryUsageTelemetrySink,
    NonBlockingLedgerStore,
    NoopUsageTelemetrySink,
    PriceBook,
    PriceEntry,
    SqlLedgerStore,
    UsageTelemetryEvent,
    UsageTelemetryHealth,
    UsageTelemetrySink,
    UsageRecord,
    dimension_catalog,
)
from .cost_router import CostRoutingCoordinator
from .credentials import NotConfigured, get_credential, register_credential
from .kv_config import InMemoryConfigStore, get_config_store
from .model_fallback import (
    CandidateValidationError,
    CostTier,
    FallbackCandidate,
    FallbackContext,
    FallbackManifestError,
    FallbackPlan,
    NoEligibleCandidateError,
    SkippedCandidate,
    build_fallback_plan,
    load_fallback_manifest,
)
from .orchestrator import (
    ModelAgent,
    ModelClient as _ModelClient,
    OrchestrationPolicy,
    TaskOrchestrator,
    WorkflowStep,
    load_agents,
)
from .provider_transport import install_provider_transport as _install_provider_transport
from .reasoning_control import (
    CANONICAL_REASONING_LEVELS,
    PayloadRule,
    ReasoningAblationCell,
    ReasoningDecision,
    ReasoningPolicy,
    ReasoningProfile,
    ReasoningWorkload,
    adapt_reasoning_decision,
    apply_reasoning_payload,
    escalate_reasoning_decision,
    extract_reasoning_tokens,
    select_reasoning_decision,
    sum_usage_tokens,
)
from .reasoning_runtime import (
    agent_reasoning_profile,
    configure_agent_reasoning,
    configure_orchestrator_reasoning,
    current_reasoning_decision,
    install_reasoning_control as _install_reasoning_control,
    orchestrator_reasoning_policy,
    reasoning_override,
)
from .token_counting import HeuristicTokenCounter, build_token_counter

_install_provider_transport(_ModelClient)
_install_reasoning_control(ModelAgent, _ModelClient, TaskOrchestrator, OrchestrationPolicy)

__all__ = [
    "ModelAgent",
    "TaskOrchestrator",
    "WorkflowStep",
    "load_agents",
    "get_credential",
    "register_credential",
    "NotConfigured",
    # cost review
    "ATTRIBUTION_DIMENSIONS",
    "AttributionDimensions",
    "CostLedger",
    "InMemoryLedgerStore",
    "InMemoryUsageTelemetrySink",
    "NonBlockingLedgerStore",
    "NoopUsageTelemetrySink",
    "SqlLedgerStore",
    "PriceBook",
    "PriceEntry",
    "UsageRecord",
    "UsageTelemetryEvent",
    "UsageTelemetryHealth",
    "UsageTelemetrySink",
    "dimension_catalog",
    # config / tokens
    "InMemoryConfigStore",
    "get_config_store",
    "HeuristicTokenCounter",
    "build_token_counter",
    # routing / batch
    "RoutingPolicy",
    "RoutingHints",
    "RoutingDecision",
    "BatchRequest",
    "BatchJob",
    "BatchResultItem",
    "LocalBatchBackend",
    "PgLlmBatchBackend",
    # embeddings batch
    "EmbeddingBatchRequest",
    "EmbeddingBatchResultItem",
    "LocalEmbeddingBatchBackend",
    "PgLlmBatchEmbeddingBackend",
    "heuristic_embedding",
    "build_embeddings_jsonl_body",
    "cheapest_upstream",
    "CostRoutingCoordinator",
    # transport-neutral model fallback policy
    "CandidateValidationError",
    "CostTier",
    "FallbackCandidate",
    "FallbackContext",
    "FallbackManifestError",
    "FallbackPlan",
    "NoEligibleCandidateError",
    "SkippedCandidate",
    "build_fallback_plan",
    "load_fallback_manifest",
    # adaptive provider reasoning control
    "CANONICAL_REASONING_LEVELS",
    "PayloadRule",
    "ReasoningAblationCell",
    "ReasoningDecision",
    "ReasoningPolicy",
    "ReasoningProfile",
    "ReasoningWorkload",
    "adapt_reasoning_decision",
    "apply_reasoning_payload",
    "escalate_reasoning_decision",
    "extract_reasoning_tokens",
    "select_reasoning_decision",
    "sum_usage_tokens",
    "agent_reasoning_profile",
    "configure_agent_reasoning",
    "configure_orchestrator_reasoning",
    "current_reasoning_decision",
    "orchestrator_reasoning_policy",
    "reasoning_override",
]
