"""Public package exports for the contextual orchestration runtime."""

from .batch_routing import (
    BatchJob,
    BatchRequest,
    BatchResultItem,
    EmbeddingBatchRequest,
    EmbeddingBatchResultItem,
    LocalBatchBackend,
    LocalEmbeddingBatchBackend,
    PgLlmBatchBackend,
    PgLlmBatchEmbeddingBackend,
    RoutingDecision,
    RoutingHints,
    RoutingPolicy,
    build_embeddings_jsonl_body,
    cheapest_upstream,
    heuristic_embedding,
)
from .cost_ledger import (
    ATTRIBUTION_DIMENSIONS,
    AttributionDimensions,
    CostLedger,
    InMemoryLedgerStore,
    InMemoryUsageTelemetrySink,
    NonBlockingLedgerStore,
    NoopUsageTelemetrySink,
    PriceBook,
    PriceEntry,
    SqlLedgerStore,
    UsageTelemetryEvent,
    UsageTelemetryHealth,
    UsageTelemetrySink,
    UsageRecord,
    dimension_catalog,
)
from .cost_router import CostRoutingCoordinator
from .credentials import NotConfigured, get_credential, register_credential
from .kv_config import InMemoryConfigStore, get_config_store
from .orchestrator import ModelAgent, TaskOrchestrator, WorkflowStep, known_price_rank, load_agents
from .provider_catalog import (
    DEFAULT_PROVIDER_ACCOUNTS,
    CatalogHttpError,
    CatalogModelRecord,
    DiscoveredModel,
    InMemoryProviderCatalogStore,
    ProviderAccount,
    ProviderAwareModelClient,
    ProviderCatalogHttpClient,
    ProviderCatalogService,
    ProviderCatalogUnavailable,
    bootstrap_provider_credentials,
    build_catalog_orchestrator,
    known_catalog_prices,
    normalize_models_document,
    refresh_and_overlay,
)
from .token_counting import HeuristicTokenCounter, build_token_counter

__all__ = [
    "ModelAgent",
    "TaskOrchestrator",
    "WorkflowStep",
    "load_agents",
    "known_price_rank",
    "get_credential",
    "register_credential",
    "NotConfigured",
    # provider catalog (PR #574 inventory/refresh on main)
    "DEFAULT_PROVIDER_ACCOUNTS",
    "ProviderAccount",
    "DiscoveredModel",
    "CatalogModelRecord",
    "CatalogHttpError",
    "ProviderCatalogUnavailable",
    "InMemoryProviderCatalogStore",
    "ProviderCatalogHttpClient",
    "ProviderAwareModelClient",
    "ProviderCatalogService",
    "bootstrap_provider_credentials",
    "normalize_models_document",
    "known_catalog_prices",
    "refresh_and_overlay",
    "build_catalog_orchestrator",
    # cost review
    "ATTRIBUTION_DIMENSIONS",
    "AttributionDimensions",
    "CostLedger",
    "InMemoryLedgerStore",
    "InMemoryUsageTelemetrySink",
    "NonBlockingLedgerStore",
    "NoopUsageTelemetrySink",
    "SqlLedgerStore",
    "PriceBook",
    "PriceEntry",
    "UsageRecord",
    "UsageTelemetryEvent",
    "UsageTelemetryHealth",
    "UsageTelemetrySink",
    "dimension_catalog",
    # config / tokens
    "InMemoryConfigStore",
    "get_config_store",
    "HeuristicTokenCounter",
    "build_token_counter",
    # routing / batch
    "RoutingPolicy",
    "RoutingHints",
    "RoutingDecision",
    "BatchRequest",
    "BatchJob",
    "BatchResultItem",
    "LocalBatchBackend",
    "PgLlmBatchBackend",
    # embeddings batch
    "EmbeddingBatchRequest",
    "EmbeddingBatchResultItem",
    "LocalEmbeddingBatchBackend",
    "PgLlmBatchEmbeddingBackend",
    "heuristic_embedding",
    "build_embeddings_jsonl_body",
    "cheapest_upstream",
    "CostRoutingCoordinator",
]
